name: build
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]
    paths:
      - "**.sh"
      - Dockerfile
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: ./
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: v8.${{ env.minor }}.${{ env.patch }}
          path: /home/runner/work/_temp/_github_home/nginx.deb
      - name: Update
        if: ${{ env.change }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update hash and version
      - name: Release
        if: ${{ env.change }}
        uses: softprops/action-gh-release@v1
        with:
          files: /home/runner/work/_temp/_github_home/nginx.deb
          body: "SHA256: ${{ env.hash }}"
          tag_name: v8.${{ env.minor }}.${{ env.patch }}
          generate_release_notes: false
