on:
  schedule:
  - cron: '0 0 * * *'
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: NGINX build
    steps:
      - name: NGINX build
        uses: ./
      - name: Upload build
        uses: actions/upload-artifact@v3.0.0
        with:
          name: nginx-${{ github.sha }}.deb
          path: nginx.deb
