name: NGINX build
on:
  schedule:
  - cron: '0 0 * * *'
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: NGINX build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: ./
      - name: Add hash
        run: |
          cd /home/runner/work/_temp/_github_home
          export hash=$(md5sum nginx.deb | awk '{print $1}')
          mv nginx.deb nginx-$hash.deb
      - name: Upload
        uses: actions/upload-artifact@v3.0.0
        with:
          name: nginx-${{ env.hash }}.deb
          path: /home/runner/work/_temp/_github_home/nginx-${{ env.hash }}.deb
